services:
    app:
        build: .
        container_name: spring_app
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/medium-docker
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
        depends_on:
            - postgres
        networks:
            - postgres-network
    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: medium-docker
        ports:
            - "5432:5432"
        networks:
            - postgres-network
        volumes:
            - /home/filipe/data/postgres:/var/lib/postgresql/data

networks:
    postgres-network:
        driver: bridge
