version: '3.8'

services:
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        environment:
            PGADMIN_DEFAULT_EMAIL: ""
            PGADMIN_DEFAULT_PASSWORD: ""
        ports:
            - "89:80"
        networks:
            - postgres-network

    postgres:
        image: postgres:10
        container_name: postgres10_container
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: medium-docker
        ports:
            - "5432:5432"
        networks:
            - postgres-network
        volumes:
            - /home/filipe/data/postgres:/var/lib/postgresql/data

networks:
    postgres-network:
        driver: bridge