version: '3.8'

services:
    app:
        build: .
        container_name: spring_app
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/teste
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
        depends_on:
            - postgres
        networks:
            - postgres-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        environment:
            PGADMIN_DEFAULT_EMAIL: "filipemourao.contato@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"
        ports:
            - "89:80"
        networks:
            - postgres-network

    postgres:
        image: postgres:10
        container_name: postgres10_container1
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: teste
        ports:
            - "5432:5432"
        networks:
            - postgres-network
        volumes:
            - /home/filipe/data/postgres:/var/lib/postgresql/data

networks:
    postgres-network:
        driver: bridge
